### ISSUE TITLE
[Feature request] Access to socket option within UDPSocket and TCPSocket

### ISSUE THREAD

**Issue by nagius** [celluloid/celluloid-io#161]
It would be nice to be able to access to setsockopt() on the socket.
For example, this is necessary for broadcasting: 

```ruby
@socket = Celluloid::IO::UDPSocket.new
@socket.bind(host, port)
@socket.setsockopt(Socket::SOL_SOCKET, Socket::SO_BROADCAST, true)
```

This doesn't work and raise an exception : <code>NoMethodError: undefined method `setsockopt'</code>

**Comment by nagius** [comment]
This monkey-patch do the trick : 

```ruby
module Celluloid
    module IO
        class UDPSocket
           def_delegators :@socket, :setsockopt
        end
    end
end
```

**Comment by TiagoCardoso1983** [comment]
@nagius Here is how it's done: https://github.com/celluloid/celluloid-io/blob/master/lib/celluloid/io/udp_socket.rb#L6 . Care to pull request?

**Comment by nagius** [comment]
Hi, 

Back from holidays, I saw that it's now working with version 0.17.3 (6bdde40fd68401fcf2d3b0b34f3a6bcf43e299ec)

Thanks !
